import './css/style.css'

import { Inter, Playfair_Display , Raleway } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'
import { SelectedUserProvider } from './contexts/selected-user-context'
import { ReactNode } from 'react'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
  adjustFontFallback: false,
})
const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
  adjustFontFallback: false,
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  adjustFontFallback: false,
}
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <SelectedUserProvider>
      <html lang="en">
        <body className={`${playfairDisplay.variable} font-playfair-display ${raleway.variable}  antialiased bg-[#002937] text-white tracking-tight`}>
          <div className="flex flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
            {children}
            {/* <Banner /> */}
          </div>
        </body>
      </html>
    </SelectedUserProvider>
  );
}
